services:
  postgres:
    image: postgres:17.4-alpine3.21
    restart: always
    env_file:
      - .env
    volumes:
      - libertai_inference_pg_data:/var/lib/postgresql/data

  migrations-postgres:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    command: [ "poetry", "run", "alembic", "upgrade", "head" ]

  inference:
    build:
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - dokploy-network
      - default

networks:
  dokploy-network:
    external: true

volumes:
  libertai_inference_pg_data:
