services:
  subscription:
    build:
      dockerfile: ./Dockerfile
    image: libertai-subscriptions
    container_name: libertai-subscriptions
    restart: unless-stopped
    ports:
      - "8081:8000"
    env_file:
      - .env
