services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: libertai-inference-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - libertai_inference_pg_data:/var/lib/postgresql/data

  inference:
    build:
      dockerfile: ./Dockerfile
    image: libertai-inference
    container_name: libertai-inference
    restart: always
    ports:
      - "8081:8000"
    env_file:
      - .env

volumes:
  libertai_inference_pg_data: