"""add_image_chats

Revision ID: 0b8b097922af
Revises: b556bf60a6be
Create Date: 2026-01-28 01:30:43.059037

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b8b097922af"
down_revision: Union[str, None] = "b556bf60a6be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_requests", sa.Column("image_count", sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_requests", "image_count")
    # ### end Alembic commands ###
