"""Added cached_tokens

Revision ID: 265fe2ea9f1b
Revises: 7d265a4eacf9
Create Date: 2025-04-09 13:27:15.111556

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '265fe2ea9f1b'
down_revision: Union[str, None] = '7d265a4eacf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference_calls', sa.Column('cached_tokens', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inference_calls', 'cached_tokens')
    # ### end Alembic commands ###
