"""invoices and billing details

Revision ID: 278cfb829fbe
Revises: d4c9b8a7f6e5
Create Date: 2026-08-24 22:54:57.134606

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "278cfb829fbe"
down_revision: str | None = "d4c9b8a7f6e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("issued_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("payment_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("external_reference", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("vat_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("line_label", sa.String(), nullable=False),
        sa.Column("period_start", sa.TIMESTAMP(), nullable=True),
        sa.Column("period_end", sa.TIMESTAMP(), nullable=True),
        sa.Column("seller", sa.JSON(), nullable=False),
        sa.Column("buyer", sa.JSON(), nullable=False),
        sa.Column("pdf", sa.LargeBinary(), nullable=True),
        sa.Column("template_version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_reference"),
        sa.UniqueConstraint("number"),
        sa.UniqueConstraint("year", "seq", name="uq_invoices_year_seq"),
        sa.Index("ix_invoices_user_id_issued_at", "user_id", "issued_at"),
    )
    op.create_table(
        "user_billing_details",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("address_line1", sa.String(length=200), nullable=True),
        sa.Column("address_line2", sa.String(length=200), nullable=True),
        sa.Column("postal_code", sa.String(length=32), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("vat_number", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_billing_details")
    op.drop_table("invoices")
    # ### end Alembic commands ###
