"""x402

Revision ID: 483879ab11ca
Revises: ade7c91f8970
Create Date: 2026-02-25 17:02:07.533545

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "483879ab11ca"
down_revision: Union[str, None] = "ade7c91f8970"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "x402_balances",
        sa.Column("user_address", sa.String(), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(["user_address"], ["users.address"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_address"),
    )
    op.execute("ALTER TYPE apikeytype ADD VALUE IF NOT EXISTS 'x402'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("x402_balances")
    # ### end Alembic commands ###
