"""add is_deleted column to api_keys

Revision ID: 6dc2425050f3
Revises: a994022883c1
Create Date: 2025-10-20 09:50:34.464041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc2425050f3'
down_revision: Union[str, None] = 'a994022883c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'api_keys',
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'is_deleted')
    # ### end Alembic commands ###
