"""liberclaw

Revision ID: 8524a5dd70f3
Revises: 0b8b097922af
Create Date: 2026-02-15 22:22:00.254105

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8524a5dd70f3"
down_revision: Union[str, None] = "0b8b097922af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "liberclaw_users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("user_type", sa.String(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "user_type", name="unique_liberclaw_user"),
    )
    op.add_column("api_keys", sa.Column("liberclaw_user_id", sa.UUID(), nullable=True))
    op.alter_column("api_keys", "user_address", existing_type=sa.VARCHAR(), nullable=True)
    op.create_foreign_key(None, "api_keys", "liberclaw_users", ["liberclaw_user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "api_keys", type_="foreignkey")
    op.alter_column("api_keys", "user_address", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("api_keys", "liberclaw_user_id")
    op.drop_table("liberclaw_users")
    # ### end Alembic commands ###
