"""empty message

Revision ID: 8c33166155b6
Revises: a7762573fc4b
Create Date: 2025-03-24 19:30:16.518252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c33166155b6'
down_revision: Union[str, None] = 'a7762573fc4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transactions', sa.Column('provider', sa.String(), nullable=True))
    op.execute("UPDATE credit_transactions SET provider = 'libertai'")
    op.alter_column('credit_transactions', 'provider', nullable=False)
    op.alter_column('credit_transactions', 'block_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_transactions', 'block_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('credit_transactions', 'provider')
    # ### end Alembic commands ###
