"""Remove agent secret

Revision ID: 94ae10b846bb
Revises: 52e4c9d4a997
Create Date: 2025-05-20 00:30:25.429008

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94ae10b846bb"
down_revision: Union[str, None] = "52e4c9d4a997"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("agents_secret_key", "agents", type_="unique")
    op.drop_column("agents", "secret")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("secret", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint("agents_secret_key", "agents", ["secret"])
    # ### end Alembic commands ###
