"""Setup

Revision ID: ac5b83fdb0cf
Revises:
Create Date: 2025-03-22 19:40:26.483634

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.

revision: str = "ac5b83fdb0cf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("address"),
    )
    op.create_table(
        "credit_balances",
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.CheckConstraint("balance >= 0", name="check_balance_non_negative"),
        sa.ForeignKeyConstraint(["address"], ["users.address"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("address"),
    )
    op.create_table(
        "credit_transactions",
        sa.Column("transaction_hash", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("usd_value", sa.Float(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.CheckConstraint("usd_value >= 0", name="check_usd_value_non_negative"),
        sa.ForeignKeyConstraint(["address"], ["users.address"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("transaction_hash"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("credit_transactions")
    op.drop_table("credit_balances")
    op.drop_table("users")
    # ### end Alembic commands ###
