"""Add transaction status

Revision ID: b2ddc7842398
Revises: e0b3ca5902de
Create Date: 2025-04-29 22:38:35.962795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ddc7842398'
down_revision: Union[str, None] = 'e0b3ca5902de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transactions', sa.Column('status', sa.Enum('pending', 'completed', name='transactionstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_transactions', 'status')
    # ### end Alembic commands ###
