"""Add transaction status

Revision ID: b2ddc7842398
Revises: e0b3ca5902de
Create Date: 2025-04-29 22:38:35.962795

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2ddc7842398"
down_revision: Union[str, None] = "e0b3ca5902de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Create the enum type
    transaction_status_enum = sa.Enum("pending", "completed", name="transactionstatus")
    transaction_status_enum.create(op.get_bind())

    # Step 2: Add the column as nullable for now
    op.add_column("credit_transactions", sa.Column("status", transaction_status_enum, nullable=True))

    # Step 3: Set default value for existing records
    op.execute("UPDATE credit_transactions SET status = 'completed'")

    # Step 4: Alter the column to be NOT NULL
    op.alter_column("credit_transactions", "status", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credit_transactions", "status")

    transaction_status_enum = sa.Enum("pending", "completed", name="transactionstatus")
    transaction_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
