"""add_image_requests

Revision ID: b556bf60a6be
Revises: a994022883c1
Create Date: 2026-01-22 23:16:22.641812

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b556bf60a6be"
down_revision: Union[str, None] = "a994022883c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inference_calls", sa.Column("image_count", sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inference_calls", "image_count")
    # ### end Alembic commands ###
