"""add_chat_api_keys

Revision ID: d3b1a4258a56
Revises: 659d90b9b412
Create Date: 2025-10-01 16:39:26.466580

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3b1a4258a56"
down_revision: Union[str, None] = "659d90b9b412"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    apikeytype = sa.Enum("api", "chat", name="apikeytype")
    apikeytype.create(op.get_bind(), checkfirst=True)

    # Add column with default value 'api'
    op.add_column("api_keys", sa.Column("type", apikeytype, nullable=False, server_default="api"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_keys", "type")
    # Drop the enum type
    sa.Enum(name="apikeytype").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
