"""Setup

Revision ID: f728108ce831
Revises: 
Create Date: 2025-03-25 21:56:23.099703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f728108ce831'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('credit_balances',
    sa.Column('address', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['address'], ['users.address'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('credit_transactions',
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('amount_left', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('expired_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("(provider = 'thirdweb') OR (provider = 'libertai' AND block_number IS NOT NULL)", name='check_block_number_required_for_provider_libertai'),
    sa.CheckConstraint("provider IN ('libertai', 'thirdweb')", name='check_provider_choices'),
    sa.CheckConstraint('amount >= 0', name='check_amount_non_negative'),
    sa.CheckConstraint('amount_left <= amount', name='check_amount_left_not_exceeding_value'),
    sa.CheckConstraint('amount_left >= 0', name='check_amount_left_non_negative'),
    sa.ForeignKeyConstraint(['address'], ['users.address'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_transactions')
    op.drop_table('credit_balances')
    op.drop_table('users')
    # ### end Alembic commands ###
