from libertai_utils.chains.index import is_address_valid
from libertai_utils.interfaces.blockchain import LibertaiChain
from pydantic import BaseModel, ValidationInfo, field_validator


class AuthMessageRequest(BaseModel):
    chain: LibertaiChain
    address: str

    @field_validator("address")
    def validate_address(cls, value, info: ValidationInfo):
        chain: LibertaiChain = info.data.get("chain")
        if not is_address_valid(chain, value):
            raise ValueError(f"Invalid address for chain {chain}")
        return value


class AuthMessageResponse(BaseModel):
    message: str


class AuthLoginRequest(BaseModel):
    chain: LibertaiChain
    address: str
    signature: str

    @field_validator("address")
    def validate_address(cls, value, info: ValidationInfo):
        chain: LibertaiChain = info.data.get("chain")
        if not is_address_valid(chain, value):
            raise ValueError(f"Invalid address for chain {chain}")
        return value


class AuthLoginResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    address: str


class AuthStatusResponse(BaseModel):
    authenticated: bool
    address: str | None = None


# --- UUID-identity auth (email / OAuth / wallet challenge / refresh) ---


class TokenPairResponse(BaseModel):
    access_token: str
    refresh_token: str
    token_type: str = "bearer"


class WalletChallengeRequest(BaseModel):
    address: str


class WalletChallengeResponse(BaseModel):
    message: str


class WalletVerifyRequest(BaseModel):
    address: str
    signature: str


class EmailLoginRequest(BaseModel):
    email: str
    # Origin of the app the user is signing in from (e.g. https://chat.libertai.io), so the
    # magic-link email points back there. Validated against an allowlist server-side; ignored
    # if missing or not allowed (falls back to FRONTEND_URL).
    redirect_base: str | None = None


class VerifyMagicLinkRequest(BaseModel):
    token: str | None = None
    email: str | None = None
    code: str | None = None


class CurrentUserResponse(BaseModel):
    id: str
    email: str | None = None
    display_name: str | None = None
    avatar_url: str | None = None
    address: str | None = None


class UpdateProfileRequest(BaseModel):
    # The user's chosen display name. Trimmed; an empty value clears it (UI then falls back to
    # email/address). Capped to keep it sane in headers/labels.
    display_name: str | None = None

    @field_validator("display_name")
    def normalize_display_name(cls, value: str | None):
        if value is None:
            return None
        trimmed = value.strip()
        if not trimmed:
            return None
        if len(trimmed) > 50:
            raise ValueError("display_name must be at most 50 characters")
        return trimmed


class ExchangeRequest(BaseModel):
    code: str
    # PKCE proof: the raw code_verifier whose SHA256 must match the stored challenge.
    # Required for codes minted with a challenge (CLI loopback); ignored otherwise.
    verifier: str | None = None


class CliCodeRequest(BaseModel):
    # PKCE: SHA256(code_verifier), base64url (no padding), generated by the CLI.
    challenge: str


class CliCodeResponse(BaseModel):
    code: str


class RefreshRequest(BaseModel):
    refresh_token: str


class LogoutRequest(BaseModel):
    # Optional: cookie-based clients log out via the session cookie and send no body;
    # token-based clients may pass a refresh_token to also revoke the session.
    refresh_token: str | None = None
